/**
 * A realistic sample learner, generated by running the real spaced-repetition
 * engine over five weeks of short sessions. Used by the sample dashboard so
 * the page can be explored without an account.
 */

import { createProgress, planSession, recordAttempt, setFocus, updateSettings } from '@signsprout/signkit';
import type { ProgressDoc } from '@signsprout/signkit';

const DAY = 24 * 60 * 60 * 1000;

export function makeSampleProgress(now: number = Date.now()): ProgressDoc {
  let seed = 20260928;
  const rnd = () => {
    seed = (seed * 1664525 + 1013904223) % 4294967296;
    return seed / 4294967296;
  };
  const span = 33;
  const start = now - span * DAY;
  let doc = createProgress(start - DAY);
  doc = updateSettings(doc, { displayName: 'Maya', childName: 'Leo' }, start);
  // Days off: a couple of busy weekends and a sick day.
  const skip = new Set([2, 5, 6, 12, 13, 19, 23, 27]);
  for (let d = 0; d <= span; d++) {
    if (skip.has(d)) continue;
    let t = start + d * DAY - 45 * 60 * 1000;
    // Late on: reviews slip a little, so a few plants need water.
    const plan = planSession(doc.cards, t, { maxNew: d % 3 === 0 ? 1 : 2, maxReviews: d > 29 ? 4 : 7 });
    for (const item of plan.items) {
      const tries = rnd() < 0.18 ? 2 : 1;
      const quality = 0.72 + rnd() * 0.27;
      const withGhost = item.kind === 'new' || rnd() < 0.3;
      doc = recordAttempt(doc, item.signId, { quality, tries, withGhost }, t, 35 + Math.round(rnd() * 55));
      t += 70 * 1000;
    }
  }
  return setFocus(doc, ['bath', 'sleep', 'book'], now - DAY);
}
